title: Southwest Vacations
description: Internal booking system for Southwest Airlines Vacations
domain: iamspring.github.io
url: https://iamspring.github.io
baseurl: /Southwest-Vacations

# GitHub Pages settings
lsi: false
safe: true
source: ./
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Theme settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# Files to be included 
include:
  - dist/
  - index.html
  - README.md

# Excludes
exclude:
  - node_modules/
  - .github/
  - cypress/
  - tests/
  - mock-backend/
  - data/
  - scripts/ 