title: Southwest Vacations
description: Internal booking system for Southwest Vacations
theme: jekyll-theme-cayman

# GitHub Pages settings
domain: iamspring.github.io
url: https://iamspring.github.io
baseurl: /Southwest-Vacations

# Output settings
markdown: kramdown
highlighter: rouge

# Exclude files from processing
exclude:
  - node_modules/
  - package.json
  - package-lock.json
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - src/
  - webpack.config.js
  - .github/
  - coverage/
  - cypress/
  - tests/
  - mock-backend/ 